version: '3.8'

services:
  todo-app:
    build: .
    ports:
      - "5004:5004"
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///todo_company.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy (opsiyonel)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - todo-app
    restart: unless-stopped

volumes:
  data:
