name: helmex-todo-app
services:
- name: web
  source_dir: /
  github:
    repo: ozmenkaya/todo
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt
  run_command: python start_app.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: SECRET_KEY
    value: f207c647dae4dd859b20bf29a98b82086f5b3e00c078bcafd35d622781b0200a
  - key: FLASK_ENV
    value: production
  - key: PORT
    value: "8080"
  # PostgreSQL database connection
  - key: DATABASE_URL
    value: ${helmex-todo-db.DATABASE_URL}
  # Mail konfigürasyonu
  - key: MAIL_SERVER
    value: smtp.gmail.com
  - key: MAIL_PORT
    value: "587"
  - key: MAIL_USE_TLS
    value: "true"
  - key: MAIL_USERNAME
    value: info@helmex.com.tr
  - key: MAIL_PASSWORD
    value: YOUR_GMAIL_APP_PASSWORD_HERE
  - key: MAIL_DEFAULT_SENDER
    value: noreply@helmex.com.tr

# PostgreSQL database - Kalıcı veri depolama için
databases:
- name: helmex-todo-db
  engine: PG
  size: db-s-dev-database
  num_nodes: 1
