name: todo-management-app
services:
- name: web
  github:
    repo: ozmenkaya/todo
    branch: main
    deploy_on_push: true
  run_command: python start_app.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: SECRET_KEY
    value: f207c647dae4dd859b20bf29a98b82086f5b3e00c078bcafd35d622781b0200a
  - key: FLASK_ENV
    value: production
  - key: PORT
    value: "8080"
  # PostgreSQL database connection
  - key: DATABASE_URL
    value: ${todo-db.DATABASE_URL}
  # Mail konfigürasyonu (Gmail SMTP için)
  # Bu değerleri gerçek mail bilgilerinizle değiştirin
  - key: MAIL_SERVER
    value: smtp.gmail.com
  - key: MAIL_PORT
    value: "587"
  - key: MAIL_USE_TLS
    value: "true"
  - key: MAIL_USERNAME
    value: info@helmex.com.tr
  - key: MAIL_PASSWORD
    value: 4866Pars
  - key: MAIL_DEFAULT_SENDER
    value: noreply@helmex.com.tr
    
# Yedekleme worker servisi
- name: backup-worker
  github:
    repo: ozmenkaya/todo
    branch: main
    deploy_on_push: true
  run_command: python start_backup_worker.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: SECRET_KEY
    value: f207c647dae4dd859b20bf29a98b82086f5b3e00c078bcafd35d622781b0200a
  - key: FLASK_ENV
    value: production
  # PostgreSQL database connection for backup
  - key: DATABASE_URL
    value: ${todo-db.DATABASE_URL}
  # Mail konfigürasyonu (backup bildirimler için)
  - key: MAIL_SERVER
    value: smtp.gmail.com
  - key: MAIL_PORT
    value: "587"
  - key: MAIL_USE_TLS
    value: "true"
  - key: MAIL_USERNAME
    value: info@helmex.com.tr
  - key: MAIL_PASSWORD
    value: 4866Pars
  - key: MAIL_DEFAULT_SENDER
    value: noreply@helmex.com.tr

# PostgreSQL database - Kalıcı veri depolama için
databases:
- name: todo-db
  engine: PG
  size: db-s-dev-database  # $7/ay
  num_nodes: 1

# Redis cache eklemek isterseniz (ilerisi için):
# - name: todo-cache
#   engine: REDIS
#   size: db-s-dev-database

# Custom domain eklemek isterseniz:
# domains:
# - domain: yourdomain.com
#   type: PRIMARY
# - domain: www.yourdomain.com
#   type: ALIAS
