alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: helmex-todo-db
  version: "14"
envs:
- key: MAIL_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: info@helmex.com.tr
- key: MAIL_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: iauzzcajyoqzxxkd
- key: MAIL_SERVER
  scope: RUN_AND_BUILD_TIME
  value: smtp.gmail.com
- key: MAIL_PORT
  scope: RUN_AND_BUILD_TIME
  value: "587"
- key: MAIL_USE_TLS
  scope: RUN_AND_BUILD_TIME
  value: "true"
- key: MAIL_DEFAULT_SENDER
  scope: RUN_AND_BUILD_TIME
  value: info@helmex.com.tr
- key: SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  value: f207c647dae4dd859b20bf29a98b82086f5b3e00c078bcafd35d622781b0200a
- key: FLASK_ENV
  scope: RUN_AND_BUILD_TIME
  value: production
- key: PORT
  scope: RUN_AND_BUILD_TIME
  value: "8080"
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: todo
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: stingray-app
region: fra
services:
- environment_slug: python
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${helmex-todo-db.DATABASE_URL}
  github:
    branch: main
    deploy_on_push: true
    repo: ozmenkaya/todo
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: todo
  run_command: python start_app.py
  source_dir: /
